steps:
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '-t'
    - 'europe-west1-docker.pkg.dev/$PROJECT_ID/app-repo/flask-loop-app'
    - '.'
images:
- 'europe-west1-docker.pkg.dev/$PROJECT_ID/app-repo/flask-loop-app'
